server {
	listen 0.0.0.0:8080;
	server_name example.com;
	root /tmp/webserv/example;

	location / {
		methods GET;
		index index.html;
		autoindex off;
	}

	location /images {
		methods GET;
		autoindex on;
	}

	location /images/private {
		methods GET POST;
		autoindex off;
	}
}

server {
	listen 0.0.0.0:8080;
	server_name test.com;
	root /tmp/webserv/test;

	location / {
		methods GET;
		root /tmp/webserv/test;
		index index.html;
		autoindex off;
	}
}