server {
    listen 0.0.0.0:8080;
    root /var/www;
	client_max_body_size 1000000;
	error_page 404 /errors/404.html;

    location / {
        methods GET;
        index index.html;
		upload_dir /var/www/uploads;
		autoindex off;
		redirect 301 /new-page;
    }

    location /images {
        methods GET;
        root /srv/images;
        index gallery.html;
		autoindex on;
    }

    location /upload {
        methods POST DELETE;
    }

	location /cgi-bin {
    	methods GET POST;
    	root /var/www/cgi-bin;

		cgi_handler .py /usr/bin/python3;
		cgi_handler .py /usr/local/bin/python3;
	}
}