server {
    listen 0.0.0.0:8080;
    root /var/www;

    location / {
        methods GET;
        index index.html;
    }

    location /images {
        methods GET;
        root /srv/images;
        index gallery.html;
    }

    location /upload {
        methods POST DELETE;
    }
}